# configuration file for development environment

# the logger engine to use
# console: log messages to STDOUT (your console where you started the
#          application server)
# file:    log message to a file. log directory is defined in app.pl 
logger: "file"

# the log level for this environement
# core is the lowest, it shows Dancer's core log messages as well as yours
# (debug, warning and error)
log: "debug"

# should Dancer consider warnings as critical errors?
warnings: 1 

# should Dancer show a stacktrace when an error is caught?
show_errors: 1 

# what type of session handling do you want Dancer to use?
session: "PSGI"

# cache route resolution for maximum performance
route_cache: 1
